version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: student_payment_db
    environment:
      POSTGRES_DB: student_payment_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - student_payment_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: student_payment_backend
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: student_payment_tracker
      DB_USER: postgres
      DB_PASSWORD: password
      PORT: 3001
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - student_payment_network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: student_payment_frontend
    environment:
      REACT_APP_API_BASE_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - student_payment_network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  student_payment_network:
    driver: bridge
